import AssertBytes240.Algebra.GradeDescent
import AssertBytes240.Algebra.ParamSystem

/-!
# W2 + W4 — A weakly regular sequence of generic combinations

Proves `exists_weaklyRegular_in_span`: from a 0-dimensional ideal generated by
`n` bounded-degree polynomials, choose `n` linear combinations forming a weakly
regular sequence. This is the generic-sequence input to `CIBezout`.
-/

open RingTheory.Sequence MvPolynomial
open scoped Pointwise

private lemma ideal_le_annihilator_quotient_smul_top
    {R : Type*} [CommRing R] (I : Ideal R) :
    I ≤ Module.annihilator R (R ⧸ (I • ⊤ : Submodule R R)) := by
  intro x hx
  rw [Module.mem_annihilator]
  intro y
  obtain ⟨r, rfl⟩ := Submodule.mkQ_surjective (I • ⊤ : Submodule R R) y
  rw [← map_smul, Submodule.mkQ_apply, Submodule.Quotient.mk_eq_zero]
  exact Submodule.smul_mem_smul hx trivial

private def quotAppendEquivQuotSMulTop
    {R : Type*} [CommRing R] (hs : List R) (h : R) :
    (R ⧸ (Ideal.ofList (hs ++ [h]) • ⊤ : Submodule R R)) ≃ₗ[R]
      QuotSMulTop h (R ⧸ (Ideal.ofList hs • ⊤ : Submodule R R)) :=
  Submodule.quotEquivOfEq _ _ (by
      rw [Ideal.ofList_append, Ideal.ofList_singleton, Submodule.sup_smul,
        Submodule.ideal_span_singleton_smul]) ≪≫ₗ
    (Submodule.quotientQuotientEquivQuotientSup
      (Ideal.ofList hs • ⊤ : Submodule R R) (h • ⊤ : Submodule R R)).symm ≪≫ₗ
      Submodule.quotEquivOfEq _ _ (by
        rw [Submodule.map_pointwise_smul, Submodule.map_top, Submodule.range_mkQ])

private lemma isMaximal_of_prime_over_finiteDim
    {K : Type*} [Field K] {n : ℕ}
    (I : Ideal (MvPolynomial (Fin n) K))
    [FiniteDimensional K (MvPolynomial (Fin n) K ⧸ I)]
    {P : Ideal (MvPolynomial (Fin n) K)} (hP : P.IsPrime) (hIP : I ≤ P) :
    P.IsMaximal := by
  let R := MvPolynomial (Fin n) K
  haveI hk : Ring.KrullDimLE 0 (R ⧸ I) :=
    (Module.finite_iff_krullDimLE_zero K (R ⧸ I)).mp inferInstance
  have h𝕮 : (P.map (Ideal.Quotient.mk I)).IsPrime :=
    Ideal.map_isPrime_of_surjective Ideal.Quotient.mk_surjective
      (le_trans (le_of_eq Ideal.mk_ker) hIP)
  have h𝕮max : (P.map (Ideal.Quotient.mk I)).IsMaximal :=
    Ring.krullDimLE_zero_iff.mp hk _ h𝕮
  have hcm := Ideal.comap_isMaximal_of_surjective (Ideal.Quotient.mk I)
    Ideal.Quotient.mk_surjective (K := P.map (Ideal.Quotient.mk I)) (H := h𝕮max)
  rwa [Ideal.comap_map_of_surjective _ Ideal.Quotient.mk_surjective,
    ← RingHom.ker_eq_comap_bot, Ideal.mk_ker, sup_eq_left.mpr hIP] at hcm

private lemma associated_not_isMaximal_of_invariant
    {K : Type*} [Field K] {n k : ℕ}
    (hs : List (MvPolynomial (Fin n) K))
    (hshlen : hs.length = k) (hk : k < n)
    (hinv : ∀ m : Ideal (MvPolynomial (Fin n) K), m.IsMaximal →
      Ideal.ofList hs ≤ m →
        ∃ zs : List (MvPolynomial (Fin n) K),
          zs.length = n - hs.length ∧
          (∀ z ∈ zs, z ∈ m) ∧
          IsWeaklyRegular
            ((MvPolynomial (Fin n) K) ⧸
              (Ideal.ofList hs • ⊤ :
                Submodule (MvPolynomial (Fin n) K) (MvPolynomial (Fin n) K)))
            zs) :
    ∀ P : Ideal (MvPolynomial (Fin n) K),
      P ∈ associatedPrimes (MvPolynomial (Fin n) K)
        ((MvPolynomial (Fin n) K) ⧸
          (Ideal.ofList hs • ⊤ :
            Submodule (MvPolynomial (Fin n) K) (MvPolynomial (Fin n) K))) →
      ¬ P.IsMaximal := by
  intro P hPass hPmax
  let R := MvPolynomial (Fin n) K
  let M := R ⧸ (Ideal.ofList hs • ⊤ : Submodule R R)
  have hJleAnn : Ideal.ofList hs ≤ Module.annihilator R M :=
    ideal_le_annihilator_quotient_smul_top (R := R) (Ideal.ofList hs)
  have hAnnleP : Module.annihilator R M ≤ P :=
    le_of_eq_of_le Submodule.annihilator_top.symm
      (IsAssociatedPrime.annihilator_le (AssociatePrimes.mem_iff.mp hPass))
  have hJleP : Ideal.ofList hs ≤ P := hJleAnn.trans hAnnleP
  obtain ⟨zs, hzlen, hzmem, hzwreg⟩ := hinv P hPmax hJleP
  have hzpos : 0 < zs.length := by
    rw [hzlen, hshlen]
    omega
  let z : R := zs[0]'hzpos
  have hzInList : z ∈ zs := by
    dsimp [z]
    exact List.getElem_mem hzpos
  have hzP : z ∈ P := hzmem z hzInList
  have hzreg : IsSMulRegular M z := by
    have hzreg0 := hzwreg.regular_mod_prev 0 hzpos
    let e : (M ⧸
        (Ideal.ofList (zs.take 0) • ⊤ : Submodule R M)) ≃ₗ[R] M :=
      Submodule.quotEquivOfEqBot
        (Ideal.ofList (zs.take 0) • ⊤ : Submodule R M)
        (by rw [List.take_zero, Ideal.ofList_nil, Submodule.bot_smul])
    exact (e.isSMulRegular_congr z).mp (by simpa [z] using hzreg0)
  have hzUnion : z ∈ ⋃ p ∈ associatedPrimes R M, (p : Set R) := by
    exact Set.mem_iUnion.mpr ⟨P, Set.mem_iUnion.mpr ⟨hPass, hzP⟩⟩
  rw [biUnion_associatedPrimes_eq_compl_regular R M] at hzUnion
  exact hzUnion hzreg

private lemma isSMulRegular_of_avoids_associatedPrimes_finset
    {R M : Type*} [CommRing R] [IsNoetherianRing R]
    [AddCommGroup M] [Module R M]
    (hfinite : (associatedPrimes R M).Finite) {x : R}
    (hx : ∀ P ∈ hfinite.toFinset, x ∉ P) :
    IsSMulRegular M x := by
  have hnotUnion : x ∉ ⋃ P ∈ associatedPrimes R M, (P : Set R) := by
    intro hmem
    rcases Set.mem_iUnion.mp hmem with ⟨P, hmem⟩
    rcases Set.mem_iUnion.mp hmem with ⟨hPass, hxP⟩
    exact hx P (hfinite.mem_toFinset.mpr hPass) hxP
  have hnotCompl : x ∉ ({r : R | IsSMulRegular M r}ᶜ) := by
    rwa [← biUnion_associatedPrimes_eq_compl_regular R M]
  simpa using hnotCompl

/-- **W2+W4.** Inside the `K`-span of the generators of a 0-dimensional ideal
there is a weakly regular sequence of full length `n`. -/
theorem exists_weaklyRegular_in_span
    {K : Type*} [Field K] [IsAlgClosed K] {n : ℕ}
    (g : Fin n → MvPolynomial (Fin n) K)
    [FiniteDimensional K
      (MvPolynomial (Fin n) K ⧸ Ideal.span (Set.range g))] :
    ∃ hs : List (MvPolynomial (Fin n) K),
      hs.length = n ∧
      (∀ x ∈ hs, x ∈ Submodule.span K (Set.range g)) ∧
      IsWeaklyRegular (MvPolynomial (Fin n) K) hs := by
  classical
  let R := MvPolynomial (Fin n) K
  let W : Submodule K R := Submodule.span K (Set.range g)
  let Inv : List R → Prop := fun hs =>
    ∀ m : Ideal R, m.IsMaximal → Ideal.ofList hs ≤ m →
      ∃ zs : List R,
        zs.length = n - hs.length ∧
        (∀ z ∈ zs, z ∈ m) ∧
        IsWeaklyRegular (R ⧸ (Ideal.ofList hs • ⊤ : Submodule R R)) zs
  have haux :
      ∀ k : ℕ, k ≤ n →
        ∃ hs : List R,
          hs.length = k ∧
          (∀ x ∈ hs, x ∈ W) ∧
          IsWeaklyRegular R hs ∧
          Inv hs := by
    intro k
    induction k with
    | zero =>
        intro _hk
        refine ⟨[], rfl, by simp, IsWeaklyRegular.nil R R, ?_⟩
        intro m hm _hle
        obtain ⟨a, hm_eq⟩ := MvPolynomial.eq_vanishingIdeal_singleton_of_isMaximal K hm
        let zs : List R :=
          (List.finRange n).map (fun i => MvPolynomial.X i - MvPolynomial.C (a i))
        refine ⟨zs, by simp [zs], ?_, ?_⟩
        · intro z hz
          rw [hm_eq]
          rcases List.mem_map.mp hz with ⟨i, _hi, rfl⟩
          rw [MvPolynomial.mem_vanishingIdeal_singleton_iff]
          simp
        · have hreg := translated_coords_isWeaklyRegular (K := K) a
          exact ((Submodule.quotEquivOfEqBot
            (Ideal.ofList ([] : List R) • ⊤ : Submodule R R)
            (by rw [Ideal.ofList_nil, Submodule.bot_smul])).isWeaklyRegular_congr zs).mpr hreg
    | succ k ih =>
        intro hk_succ
        obtain ⟨hs, hlen, hmem, hreg, hinv⟩ := ih (Nat.le_of_succ_le hk_succ)
        have hklt : k < n := Nat.lt_of_succ_le hk_succ
        let M := R ⧸ (Ideal.ofList hs • ⊤ : Submodule R R)
        have hfinite : (associatedPrimes R M).Finite := associatedPrimes.finite R M
        have hNoMax :
            ∀ P : Ideal R, P ∈ associatedPrimes R M → ¬ P.IsMaximal :=
          associated_not_isMaximal_of_invariant (K := K) (n := n) (k := k)
            hs hlen hklt hinv
        have havoidSub :
            ∀ P ∈ hfinite.toFinset, ¬ W ≤ Submodule.restrictScalars K P := by
          intro P hPmem hWP
          have hPass : P ∈ associatedPrimes R M := hfinite.mem_toFinset.mp hPmem
          have hPprime : P.IsPrime := (AssociatePrimes.mem_iff.mp hPass).1
          have hIleP : Ideal.span (Set.range g) ≤ P := by
            rw [Ideal.span_le]
            intro x hx
            exact hWP (Submodule.subset_span hx)
          have hPmax : P.IsMaximal :=
            isMaximal_of_prime_over_finiteDim (K := K) (n := n)
              (Ideal.span (Set.range g)) hPprime hIleP
          exact hNoMax P hPass hPmax
        obtain ⟨h, hW, havoid⟩ :=
          ParamSystem.exists_mem_avoiding_finset W hfinite.toFinset havoidSub
        have hreg_h : IsSMulRegular M h :=
          isSMulRegular_of_avoids_associatedPrimes_finset (R := R) (M := M)
            hfinite havoid
        have hreg_new : IsWeaklyRegular R (hs ++ [h]) := by
          rw [isWeaklyRegular_append_iff]
          exact ⟨hreg, (isWeaklyRegular_singleton_iff M h).mpr hreg_h⟩
        have hmem_new : ∀ x ∈ hs ++ [h], x ∈ W := by
          intro x hx
          rcases List.mem_append.mp hx with hx | hx
          · exact hmem x hx
          · simpa [List.mem_singleton.mp hx] using hW
        have hinv_new : Inv (hs ++ [h]) := by
          intro m hm hmle
          have hle_old : Ideal.ofList hs ≤ m := by
            have hsub : Ideal.ofList hs ≤ Ideal.ofList (hs ++ [h]) := by
              rw [Ideal.ofList_append]
              exact le_sup_left
            exact hsub.trans hmle
          have hh_mem : h ∈ m := by
            apply hmle
            rw [Ideal.ofList]
            exact Ideal.subset_span (by simp)
          obtain ⟨zs, hzlen, hzmem, hzwreg⟩ := hinv m hm hle_old
          haveI : Module.Finite R M := inferInstance
          obtain ⟨zs', hzs'len, hzs'mem, hzs'wreg⟩ :=
            grade_descent (S := R) (M := M) m hh_mem hreg_h zs hzmem hzwreg
          refine ⟨zs', ?_, hzs'mem, ?_⟩
          · rw [hzs'len, hzlen]
            simp [hlen]
            omega
          · exact ((quotAppendEquivQuotSMulTop (R := R) hs h).isWeaklyRegular_congr
              zs').mpr hzs'wreg
        refine ⟨hs ++ [h], by simp [hlen], hmem_new, hreg_new, hinv_new⟩
  obtain ⟨hs, hlen, hmem, hreg, _hinv⟩ := haux n le_rfl
  exact ⟨hs, hlen, hmem, hreg⟩
