import Mathlib

/-!
# T2-W0 — grade ≥ height in polynomial rings (weak-grade Cohen–Macaulayness)

Shows that a prime of a polynomial ring contains weakly regular sequences up
to its height after localizing at that prime. The arbitrary-field theorem
`grade_ge_height_field` supplies the grade-height input for the recurrence.
-/

open RingTheory.Sequence Polynomial
open scoped Pointwise

namespace GradeHeight

/-- A nonzerodivisor mod `J` (nonzero in the domain `R ⧸ J`) is `IsSMulRegular` on
the module `R ⧸ (J • ⊤)` — the shape produced by `isWeaklyRegular_append_iff`. -/
theorem smulRegular_of_quot_domain {R : Type*} [CommRing R] (J : Ideal R) (P : R)
    [IsDomain (R ⧸ J)] (hP : Ideal.Quotient.mk J P ≠ 0) :
    IsSMulRegular (R ⧸ (J • ⊤ : Submodule R R)) P := by
  have hJs : (J • ⊤ : Submodule R R) = (J : Submodule R R) := by simp
  intro a b hab
  obtain ⟨a, rfl⟩ := Submodule.Quotient.mk_surjective _ a
  obtain ⟨b, rfl⟩ := Submodule.Quotient.mk_surjective _ b
  have hab' : (Submodule.Quotient.mk (P • a) : R ⧸ (J • ⊤ : Submodule R R))
      = Submodule.Quotient.mk (P • b) := by
    rw [Submodule.Quotient.mk_smul, Submodule.Quotient.mk_smul]; exact hab
  rw [Submodule.Quotient.eq, hJs] at hab'
  rw [Submodule.Quotient.eq, hJs]
  have hmem : P * (a - b) ∈ J := by
    rw [smul_eq_mul, smul_eq_mul, ← mul_sub] at hab'; exact hab'
  have hz : Ideal.Quotient.mk J (a - b) = 0 := by
    have h0 : Ideal.Quotient.mk J (P * (a - b)) = 0 := Ideal.Quotient.eq_zero_iff_mem.mpr hmem
    rw [map_mul] at h0
    exact (mul_eq_zero.mp h0).resolve_left hP
  exact Ideal.Quotient.eq_zero_iff_mem.mp hz

open Polynomial in
/-- **Inductive step of Step 2, over a univariate polynomial extension.**
Let `A` be a Jacobson (Noetherian) ring for which every maximal ideal is
generated by a weakly regular sequence of length `qlen`. Then every maximal
ideal `m` of `A[X]` is generated by a weakly regular sequence of length
`qlen + 1`.

Proof: `mA := m.comap C` is maximal (`isMaximal_comap_C_of_isJacobsonRing`),
so the hypothesis gives a length-`qlen` weakly regular generating list `qs` of
`mA`. Set `J := Ideal.ofList (qs.map C) = mA.map C`. Then `A[X] ⧸ J ≅ (A⧸mA)[X]`
(`Ideal.polynomialQuotientEquivQuotientPolynomial`), a polynomial ring over the
field `A⧸mA`, hence a PID and a domain. Since `m ⊋ J`, the ideal `m ⧸ J` is
principal `= (P̄)` with `P̄ ≠ 0`; lift to `P ∈ m`. Then `qs.map C` is weakly
regular on `A[X]` (flat base change `A → A[X]`) and `P` is a nonzerodivisor
mod `J` (it is nonzero in the domain `(A⧸mA)[X]`), so `qs.map C ++ [P]` is
weakly regular; and `J + (P) = m`. -/
theorem polyStep {A : Type*} [CommRing A] [IsJacobsonRing A] [IsNoetherianRing A]
    (qlen : ℕ)
    (hIH : ∀ (mA : Ideal A), mA.IsMaximal → ∃ qs : List A,
      qs.length = qlen ∧ (∀ r ∈ qs, r ∈ mA) ∧ IsWeaklyRegular A qs ∧ Ideal.ofList qs = mA)
    (m : Ideal A[X]) (hm : m.IsMaximal) :
    ∃ rs : List A[X], rs.length = qlen + 1 ∧ (∀ r ∈ rs, r ∈ m) ∧
      IsWeaklyRegular A[X] rs ∧ Ideal.ofList rs = m := by
  classical
  haveI := hm
  have hmAmax : (Ideal.comap (C : A →+* A[X]) m).IsMaximal :=
    isMaximal_comap_C_of_isJacobsonRing m
  set mA : Ideal A := Ideal.comap (C : A →+* A[X]) m with hmAdef
  obtain ⟨qs, hqlen, hqmem, hqreg, hqgen⟩ := hIH mA hmAmax
  set J : Ideal A[X] := Ideal.ofList (qs.map C) with hJdef
  have hJeq : J = Ideal.map (C : A →+* A[X]) mA := by rw [hJdef, ← Ideal.map_ofList, hqgen]
  letI fld : Field (A ⧸ mA) := Ideal.Quotient.field mA
  letI : EuclideanDomain (A ⧸ mA)[X] := @Polynomial.instEuclideanDomain (A ⧸ mA) fld
  haveI pidF : IsPrincipalIdealRing (A ⧸ mA)[X] := EuclideanDomain.to_principal_ideal_domain
  let e2 : (A[X] ⧸ J) ≃+* (A ⧸ mA)[X] :=
    (Ideal.quotEquivOfEq hJeq).trans (Ideal.polynomialQuotientEquivQuotientPolynomial mA).symm
  haveI hdom : IsDomain (A[X] ⧸ J) := MulEquiv.isDomain (A ⧸ mA)[X] e2
  haveI hpid : IsPrincipalIdealRing (A[X] ⧸ J) :=
    IsPrincipalIdealRing.of_surjective e2.symm.toRingHom e2.symm.surjective
  have hJm : J ≤ m := by rw [hJeq, hmAdef]; exact Ideal.map_comap_le
  have hkerJ : Ideal.comap (Ideal.Quotient.mk J) ⊥ = J := by
    rw [← RingHom.ker_eq_comap_bot, Ideal.mk_ker]
  have hmJne : m ≠ J := by
    intro h
    have hfield : IsField (A[X] ⧸ J) := by
      rw [← h]; exact (Ideal.Quotient.maximal_ideal_iff_isField_quotient m).mp hm
    exact (Polynomial.not_isField (A ⧸ mA)) (MulEquiv.isField hfield e2.symm.toMulEquiv)
  obtain ⟨gbar, hgbar⟩ := (hpid.principal (Ideal.map (Ideal.Quotient.mk J) m)).principal
  obtain ⟨P, rfl⟩ := Ideal.Quotient.mk_surjective gbar
  have hPm : P ∈ m := by
    have h1 : Ideal.Quotient.mk J P ∈ Ideal.map (Ideal.Quotient.mk J) m := by
      rw [hgbar]; exact Ideal.mem_span_singleton_self _
    have h2 : P ∈ Ideal.comap (Ideal.Quotient.mk J) (Ideal.map (Ideal.Quotient.mk J) m) := h1
    rwa [Ideal.comap_map_of_surjective _ Ideal.Quotient.mk_surjective, hkerJ,
      sup_eq_left.mpr hJm] at h2
  have hPne : Ideal.Quotient.mk J P ≠ 0 := by
    intro h0
    apply hmJne
    have hbot : Ideal.map (Ideal.Quotient.mk J) m = ⊥ := by
      rw [hgbar, h0]; exact Submodule.span_singleton_eq_bot.mpr rfl
    have hmle : m ≤ J := by
      have := (Ideal.map_eq_bot_iff_le_ker (Ideal.Quotient.mk J)).mp hbot
      rwa [Ideal.mk_ker] at this
    exact le_antisymm hmle hJm
  refine ⟨qs.map C ++ [P], ?_, ?_, ?_, ?_⟩
  · simp [hqlen]
  · intro r hr
    rcases List.mem_append.mp hr with hr | hr
    · obtain ⟨a, ha, rfl⟩ := List.mem_map.mp hr
      exact hJm (Ideal.subset_span (List.mem_map.mpr ⟨a, ha, rfl⟩))
    · rw [List.mem_singleton.mp hr]; exact hPm
  · rw [isWeaklyRegular_append_iff]
    refine ⟨?_, ?_⟩
    · have hof := hqreg.of_flat (S := A[X])
      simpa [Polynomial.algebraMap_eq] using hof
    · rw [isWeaklyRegular_singleton_iff]
      exact smulRegular_of_quot_domain J P hPne
  · rw [Ideal.ofList_append, ← hJdef, Ideal.ofList_singleton]
    have key : Ideal.map (Ideal.Quotient.mk J) (Ideal.span {P})
        = Ideal.map (Ideal.Quotient.mk J) m := by
      rw [Ideal.map_span, Set.image_singleton]; exact hgbar.symm
    have h3 := congrArg (Ideal.comap (Ideal.Quotient.mk J)) key
    rw [Ideal.comap_map_of_surjective _ Ideal.Quotient.mk_surjective,
        Ideal.comap_map_of_surjective _ Ideal.Quotient.mk_surjective, hkerJ,
        sup_eq_left.mpr hJm] at h3
    rw [sup_comm]; exact h3

open Polynomial in
/-- **Step 2: triangular structure of maximal ideals over an arbitrary field.**
Every maximal ideal `m` of `L[x₁,…,x_h]` (any field `L`) is generated by a weakly
regular sequence of length `h`. Proved by induction on `h` using
`MvPolynomial.finSuccEquiv` to view `L[x₀,…,x_h] ≅ A[X]` with
`A := L[x₁,…,x_h]`: the contraction `m ∩ A = (m).comap C` is maximal
(`Polynomial.isMaximal_comap_C_of_isJacobsonRing`), the induction hypothesis
gives a length-`h` weakly regular generating sequence `qs` of it, and
`A[X] ⧸ (m∩A)·A[X] ≅ (A ⧸ m∩A)[X] = F[X]` is a PID, so `m`'s image is principal,
giving one further nonzerodivisor `P`. The list `qs.map C ++ [P]` works. -/
theorem maximal_weaklyRegular {L : Type*} [Field L] :
    ∀ (h : ℕ) (m : Ideal (MvPolynomial (Fin h) L)), m.IsMaximal →
      ∃ rs : List (MvPolynomial (Fin h) L),
        rs.length = h ∧ (∀ r ∈ rs, r ∈ m) ∧
        IsWeaklyRegular (MvPolynomial (Fin h) L) rs ∧ Ideal.ofList rs = m := by
  intro h
  induction h with
  | zero =>
    intro m hm
    haveI := hm
    refine ⟨[], rfl, by simp, IsWeaklyRegular.nil _ _, ?_⟩
    rw [Ideal.ofList_nil]
    let ψ : MvPolynomial (Fin 0) L ≃+* L := (MvPolynomial.isEmptyAlgEquiv L (Fin 0)).toRingEquiv
    haveI : (Ideal.map ψ m).IsMaximal := Ideal.map_isMaximal_of_equiv ψ
    have hbot : Ideal.map ψ m = ⊥ := by
      rcases Ideal.eq_bot_or_top (Ideal.map ψ m) with h0 | h0
      · exact h0
      · exact absurd h0 (Ideal.map_isMaximal_of_equiv ψ).ne_top
    have hm_bot : m = ⊥ := by
      have h1 : Ideal.map ψ.symm (Ideal.map ψ m) = m := by
        rw [Ideal.map_symm]; exact Ideal.comap_map_of_bijective ψ.toRingHom ψ.bijective
      rw [← h1, hbot, Ideal.map_bot]
    rw [hm_bot]
  | succ h ih =>
    intro m hm
    haveI := hm
    let φ : MvPolynomial (Fin (h + 1)) L ≃+* (MvPolynomial (Fin h) L)[X] :=
      (MvPolynomial.finSuccEquiv L h).toRingEquiv
    haveI hm2 : (Ideal.map φ m).IsMaximal := Ideal.map_isMaximal_of_equiv φ
    obtain ⟨rs2, hlen2, hmem2, hreg2, hgen2⟩ := polyStep h ih (Ideal.map φ m) hm2
    refine ⟨rs2.map φ.symm, ?_, ?_, ?_, ?_⟩
    · rw [List.length_map, hlen2]
    · intro r hr
      obtain ⟨r0, hr0, rfl⟩ := List.mem_map.mp hr
      exact Ideal.symm_apply_mem_of_equiv_iff.mpr (hmem2 r0 hr0)
    · refine (φ.symm.toAddEquiv.isWeaklyRegular_congr
        (List.forall₂_map_right_iff.mpr (List.forall₂_same.mpr (fun r _ x => ?_)))).mp hreg2
      simp only [smul_eq_mul, RingEquiv.toAddEquiv_eq_coe, RingEquiv.coe_toAddEquiv, map_mul]
    · have key : Ideal.map φ.symm (Ideal.ofList rs2) = Ideal.ofList (rs2.map φ.symm) := by
        rw [Ideal.ofList, Ideal.ofList, Ideal.map_span]
        congr 1
        ext y
        simp [List.mem_map]
      rw [← key, hgen2, Ideal.map_symm]
      exact Ideal.comap_map_of_bijective φ.toRingHom φ.bijective

/-- **Localization transport under a ring isomorphism.** The localized weakly
regular sequence property transfers along a `RingEquiv` `φ : R ≃+* R'`. -/
theorem transport {R R' : Type*} [CommRing R] [CommRing R'] (φ : R ≃+* R')
    (Q : Ideal R) [Q.IsPrime] (h : ℕ)
    (H : ∃ rs' : List R', rs'.length = h ∧ (∀ r ∈ rs', r ∈ Ideal.map φ Q) ∧
      IsWeaklyRegular (Localization.AtPrime (Ideal.map φ Q))
        (rs'.map (algebraMap R' (Localization.AtPrime (Ideal.map φ Q))))) :
    ∃ rs : List R, rs.length = h ∧ (∀ r ∈ rs, r ∈ Q) ∧
      IsWeaklyRegular (Localization.AtPrime Q)
        (rs.map (algebraMap R (Localization.AtPrime Q))) := by
  haveI : (Ideal.map φ Q).IsPrime := Ideal.map_isPrime_of_equiv φ
  obtain ⟨rs', hlen', hmem', hreg'⟩ := H
  have hpc : Submonoid.map φ.toMonoidHom Q.primeCompl = (Ideal.map φ Q).primeCompl := by
    ext y
    constructor
    · rintro ⟨x, hx, rfl⟩
      show φ x ∉ Ideal.map φ Q
      rw [Ideal.apply_mem_of_equiv_iff]; exact hx
    · intro hy
      refine ⟨φ.symm y, ?_, φ.apply_symm_apply y⟩
      show φ.symm y ∉ Q
      rw [Ideal.symm_apply_mem_of_equiv_iff]; exact hy
  let ψ : Localization.AtPrime Q ≃+* Localization.AtPrime (Ideal.map φ Q) :=
    IsLocalization.ringEquivOfRingEquiv (Localization.AtPrime Q)
      (Localization.AtPrime (Ideal.map φ Q)) φ hpc
  have hψsymm : ∀ y : R', ψ.symm (algebraMap R' (Localization.AtPrime (Ideal.map φ Q)) y)
      = algebraMap R (Localization.AtPrime Q) (φ.symm y) := by
    intro y
    apply ψ.injective
    rw [ψ.apply_symm_apply, IsLocalization.ringEquivOfRingEquiv_eq, φ.apply_symm_apply]
  refine ⟨rs'.map φ.symm, by rw [List.length_map, hlen'], ?_, ?_⟩
  · intro r hr
    obtain ⟨r0, hr0, rfl⟩ := List.mem_map.mp hr
    exact Ideal.symm_apply_mem_of_equiv_iff.mpr (hmem' r0 hr0)
  · have hfun : (⇑ψ.symm ∘ ⇑(algebraMap R' (Localization.AtPrime (Ideal.map φ Q))))
        = (fun r0 => algebraMap R (Localization.AtPrime Q) (φ.symm r0)) := by
      funext y; exact hψsymm y
    have hcongr := (ψ.symm.toAddEquiv.isWeaklyRegular_congr
      (as := rs'.map (algebraMap R' (Localization.AtPrime (Ideal.map φ Q))))
      (bs := (rs'.map (algebraMap R' (Localization.AtPrime (Ideal.map φ Q)))).map ψ.symm)
      (List.forall₂_map_right_iff.mpr (List.forall₂_same.mpr
        (fun r _ x => by simp only [smul_eq_mul, RingEquiv.toAddEquiv_eq_coe,
          RingEquiv.coe_toAddEquiv, map_mul])))).mp hreg'
    rw [List.map_map, hfun] at hcongr
    rw [List.map_map]
    exact hcongr

/-- **Case-A transport.** A weakly regular sequence in `P` on `A_P` pushes
forward (via flatness of `A_P → (A[X])_{Q'}`, valid since `P = Q' ∩ A`) to a
weakly regular sequence in `Q'` on `(A[X])_{Q'}`. -/
theorem caseA_transport {A : Type*} [CommRing A] {P : Ideal A} [P.IsPrime]
    {Q' : Ideal A[X]} [Q'.IsPrime] (hPQ : Ideal.comap (C : A →+* A[X]) Q' = P) {rsA : List A}
    (hreg : IsWeaklyRegular (Localization.AtPrime P)
      (rsA.map (algebraMap A (Localization.AtPrime P)))) :
    IsWeaklyRegular (Localization.AtPrime Q')
      ((rsA.map C).map (algebraMap A[X] (Localization.AtPrime Q'))) := by
  have hmono : P.primeCompl ≤ Submonoid.comap (C : A →+* A[X]) Q'.primeCompl := by
    intro x hx
    show C x ∉ Q'
    rw [← Ideal.mem_comap, hPQ]; exact hx
  let g : Localization.AtPrime P →+* Localization.AtPrime Q' :=
    IsLocalization.map (Localization.AtPrime Q') (C : A →+* A[X]) hmono
  letI : Algebra (Localization.AtPrime P) (Localization.AtPrime Q') := g.toAlgebra
  haveI : IsScalarTower A (Localization.AtPrime P) (Localization.AtPrime Q') := by
    apply IsScalarTower.of_algebraMap_eq'
    ext x
    show algebraMap A (Localization.AtPrime Q') x = g (algebraMap A (Localization.AtPrime P) x)
    rw [show g (algebraMap A (Localization.AtPrime P) x)
        = algebraMap A[X] (Localization.AtPrime Q') (C x) from IsLocalization.map_eq _ x]
    rw [IsScalarTower.algebraMap_apply A A[X] (Localization.AtPrime Q')]
    rfl
  haveI : Module.Flat A (Localization.AtPrime Q') := inferInstance
  haveI : Module.Flat (Localization.AtPrime P) (Localization.AtPrime Q') :=
    (Module.flat_iff_of_isLocalization (S := Localization.AtPrime P) (R := A)
      (M := Localization.AtPrime Q') (p := P.primeCompl)).mpr inferInstance
  have hof := hreg.of_flat (S := Localization.AtPrime Q')
  rw [List.map_map] at hof
  rw [List.map_map]
  convert hof using 2
  funext a
  simp only [Function.comp_apply]
  rw [← IsScalarTower.algebraMap_apply A (Localization.AtPrime P) (Localization.AtPrime Q'),
    IsScalarTower.algebraMap_apply A A[X] (Localization.AtPrime Q'), Polynomial.algebraMap_eq]

attribute [local instance] Polynomial.algebra in
/-- A prime of `D[X]` (over a domain `D`) contracting to `⊥` has height `≤ 1`
(it becomes a prime of the PID `FractionRing D [X]`). -/
theorem fibre_height_le_one {D : Type*} [CommRing D] [IsDomain D] (𝔮 : Ideal D[X])
    [𝔮.IsPrime] (h0 : Ideal.comap (C : D →+* D[X]) 𝔮 = ⊥) : 𝔮.height ≤ 1 := by
  haveI : IsLocalization ((nonZeroDivisors D).map (C : D →+* D[X])) (FractionRing D)[X] :=
    Polynomial.isLocalization (nonZeroDivisors D) (FractionRing D)
  have hdisj : Disjoint ((nonZeroDivisors D).map (C : D →+* D[X]) : Set D[X]) (𝔮 : Set D[X]) := by
    rw [Set.disjoint_left]
    rintro x ⟨d, hd, rfl⟩ hxq
    have hd0 : d ∈ Ideal.comap (C : D →+* D[X]) 𝔮 := hxq
    rw [h0, Ideal.mem_bot] at hd0
    exact (nonZeroDivisors.ne_zero hd) hd0
  have hmap := IsLocalization.height_map_of_disjoint
    (S := (FractionRing D)[X]) ((nonZeroDivisors D).map (C : D →+* D[X])) 𝔮 hdisj
  rw [← hmap]
  haveI hpr : (𝔮.map (algebraMap D[X] (FractionRing D)[X])).IsPrime :=
    IsLocalization.isPrime_of_isPrime_disjoint
      ((nonZeroDivisors D).map (C : D →+* D[X])) (FractionRing D)[X] 𝔮 ‹_› hdisj
  have h1 : (𝔮.map (algebraMap D[X] (FractionRing D)[X])).height
      ≤ ringKrullDim (FractionRing D)[X] :=
    Ideal.height_le_ringKrullDim_of_ne_top hpr.ne_top
  have h2 : ringKrullDim (FractionRing D)[X] = 1 := by
    rw [Polynomial.ringKrullDim_of_isNoetherianRing, ringKrullDim_eq_zero_of_field (FractionRing D)]
    simp
  rw [h2] at h1
  exact_mod_cast h1

/-- **Fibre height bound.** For a prime `Q'` of `A[X]` (over a Noetherian
domain `A`) with contraction `P := Q' ∩ A`, one has `ht Q' ≤ ht P + 1`
(the fibre of `Spec A[X] → Spec A` has dimension ≤ 1). -/
theorem heightbound {A : Type*} [CommRing A] [IsNoetherianRing A] [IsDomain A]
    (Q' : Ideal A[X]) [Q'.IsPrime] :
    Q'.height ≤ (Ideal.comap (C : A →+* A[X]) Q').height + 1 := by
  set P := Ideal.comap (C : A →+* A[X]) Q' with hP
  haveI hPp : P.IsPrime := inferInstance
  haveI : Q'.LiesOver P := ⟨by rw [hP, Ideal.under_def, Polynomial.algebraMap_eq]⟩
  have hle := Ideal.height_le_height_add_of_liesOver P Q'
  refine le_trans hle ?_
  gcongr
  rw [Polynomial.algebraMap_eq]
  set I : Ideal A[X] := P.map (C : A →+* A[X]) with hI
  set e := Ideal.polynomialQuotientEquivQuotientPolynomial P with he
  set 𝔮 : Ideal (A ⧸ P)[X] := (Q'.map (Ideal.Quotient.mk I)).comap e with hq
  haveI hJp : (Q'.map (Ideal.Quotient.mk I)).IsPrime := by
    apply Ideal.map_isPrime_of_surjective Ideal.Quotient.mk_surjective
    rw [Ideal.mk_ker]; exact Ideal.map_comap_le
  haveI : 𝔮.IsPrime := Ideal.comap_isPrime e _
  rw [(RingEquiv.height_comap e _).symm]
  have hbot : Ideal.comap (C : (A ⧸ P) →+* (A ⧸ P)[X]) 𝔮 = ⊥ := by
    rw [eq_bot_iff]
    intro d hd
    rw [Ideal.mem_comap] at hd
    obtain ⟨a, rfl⟩ := Ideal.Quotient.mk_surjective d
    rw [hq, Ideal.mem_comap] at hd
    have hEC : e (C (Ideal.Quotient.mk P a)) = Ideal.Quotient.mk I (C a) := by
      have hmc : (C (Ideal.Quotient.mk P a) : (A ⧸ P)[X]) = (C a).map (Ideal.Quotient.mk P) := by
        rw [Polynomial.map_C]
      rw [hmc]
      exact Ideal.polynomialQuotientEquivQuotientPolynomial_map_mk P (C a)
    rw [hEC] at hd
    have hCaQ : C a ∈ Q' := by
      have h2 : C a ∈ Ideal.comap (Ideal.Quotient.mk I) (Q'.map (Ideal.Quotient.mk I)) := hd
      rwa [Ideal.comap_map_of_surjective _ Ideal.Quotient.mk_surjective,
        ← RingHom.ker_eq_comap_bot, Ideal.mk_ker, sup_eq_left.mpr Ideal.map_comap_le] at h2
    rw [Ideal.mem_bot, Ideal.Quotient.eq_zero_iff_mem, hP]
    exact Ideal.mem_comap.mpr hCaQ
  exact fibre_height_le_one (D := A ⧸ P) 𝔮 hbot

/-- Extended primes do not raise height: `ht (P[X]) ≤ ht P`. -/
theorem height_map_C_le {A : Type*} [CommRing A] [IsNoetherianRing A] (P : Ideal A) [P.IsPrime] :
    (Ideal.map (C : A →+* A[X]) P).height ≤ P.height := by
  haveI : (Ideal.map (C : A →+* A[X]) P).IsPrime := inferInstance
  haveI : (Ideal.map (C : A →+* A[X]) P).LiesOver P := by
    refine ⟨?_⟩
    rw [Ideal.under_def, Polynomial.algebraMap_eq]
    symm
    apply le_antisymm
    · intro a ha
      rw [Ideal.mem_comap, Ideal.mem_map_C_iff] at ha
      simpa using ha 0
    · exact Ideal.le_comap_map
  have hle := Ideal.height_le_height_add_of_liesOver P (Ideal.map (C : A →+* A[X]) P)
  have hz : ((Ideal.map (C : A →+* A[X]) P).map
      (Ideal.Quotient.mk (P.map (algebraMap A A[X])))).height = 0 := by
    rw [Polynomial.algebraMap_eq, Ideal.map_quotient_self]
    simp
  rw [hz, add_zero] at hle
  exact hle

open Polynomial in
/-- A polynomial with a unit coefficient is a nonzerodivisor, in `IsSMulRegular` form. -/
theorem polynomial_isSMulRegular_of_isUnit_coeff {R : Type*} [CommRing R] {p : R[X]} {n : ℕ}
    (hp : IsUnit (p.coeff n)) : IsSMulRegular R[X] p := by
  have hp' : p ∈ nonZeroDivisors R[X] :=
    Polynomial.mem_nonzeroDivisors_of_coeff_mem n hp.mem_nonZeroDivisors
  rw [isSMulRegular_iff_right_eq_zero_of_smul]
  intro q hq
  exact hp'.1 q (by simpa [smul_eq_mul] using hq)

set_option maxHeartbeats 800000 in
/-- **McCoy in the algebraic fibre.** If `f ∉ P[X]` (`P := Q' ∩ A`), then `f` is a
nonzerodivisor modulo `rsA` on `(A[X])_{Q'}`: passing to the local fibre
`(A_P / rsA)[X]` (a polynomial ring over a local ring), a coefficient of `f`
outside `P` becomes a unit, so `f` is a nonzerodivisor there by McCoy, and this is
preserved under the localization `(A[X])_{Q'}`. -/
theorem mccoy_fibre {A : Type*} [CommRing A] [IsNoetherianRing A] [IsDomain A]
    {Q' : Ideal A[X]} [Q'.IsPrime] (rsA : List A) (f : A[X])
    (hfP : f ∉ Ideal.map (C : A →+* A[X]) (Ideal.comap (C : A →+* A[X]) Q')) :
    IsSMulRegular
      (Localization.AtPrime Q' ⧸
        (Ideal.ofList ((rsA.map C).map (algebraMap A[X] (Localization.AtPrime Q'))) •
          (⊤ : Submodule (Localization.AtPrime Q') (Localization.AtPrime Q'))))
      (algebraMap A[X] (Localization.AtPrime Q') f) := by
  classical
  let S : Type _ := Localization.AtPrime Q'
  let JA : Ideal A := Ideal.ofList rsA
  let I : Ideal A[X] := Ideal.map (C : A →+* A[X]) JA
  let Jloc : Ideal S := Ideal.ofList ((rsA.map C).map (algebraMap A[X] S))
  let N : Submodule S S := Jloc • (⊤ : Submodule S S)
  change IsSMulRegular (S ⧸ N) (algebraMap A[X] S f)
  have hJloc : Jloc = Ideal.map (algebraMap A[X] S) I := by
    dsimp [Jloc, I, JA]
    rw [← Ideal.map_ofList, ← Ideal.map_ofList, Ideal.map_map]
  by_cases hIle : I ≤ Q'
  · have hJs : (Jloc • (⊤ : Submodule S S)) = (Jloc : Submodule S S) := by simp
    have hN : N = (Jloc : Submodule S S) := by
      dsimp [N]
      exact hJs
    rw [hN]
    let P : Ideal A := Ideal.comap (C : A →+* A[X]) Q'
    haveI hPp : P.IsPrime := inferInstance
    have hJAleP : JA ≤ P := by
      intro a ha
      exact hIle (Ideal.mem_map_of_mem (C : A →+* A[X]) ha)
    obtain ⟨n, hnP⟩ : ∃ n : ℕ, f.coeff n ∉ P := by
      by_contra h
      apply (by simpa [P] using hfP)
      rw [Ideal.mem_map_C_iff]
      intro n
      by_contra hn
      exact h ⟨n, hn⟩
    let B : Type _ := A ⧸ JA
    let pB : Ideal B := Ideal.map (Ideal.Quotient.mk JA) P
    haveI hpBprime : pB.IsPrime := by
      apply Ideal.map_isPrime_of_surjective Ideal.Quotient.mk_surjective
      rw [Ideal.mk_ker]
      exact hJAleP
    let Bp : Type _ := Localization.AtPrime pB
    let C0 : Type _ := B[X]
    let U : Type _ := Bp[X]
    letI : Algebra C0 U := Polynomial.algebra B Bp
    let e : C0 ≃+* A[X] ⧸ I := Ideal.polynomialQuotientEquivQuotientPolynomial JA
    let fB : C0 := f.map (Ideal.Quotient.mk JA)
    have hb_notpB : Ideal.Quotient.mk JA (f.coeff n) ∉ pB := by
      intro hb
      change Ideal.Quotient.mk JA (f.coeff n) ∈
        Ideal.map (Ideal.Quotient.mk JA) P at hb
      rw [Ideal.mem_quotient_iff_mem_sup] at hb
      have hmemP : f.coeff n ∈ P := by
        rwa [sup_eq_left.mpr hJAleP] at hb
      exact hnP hmemP
    have hcoeffUnit : IsUnit (algebraMap B Bp (Ideal.Quotient.mk JA (f.coeff n))) :=
      IsLocalization.map_units (M := pB.primeCompl) Bp
        ⟨Ideal.Quotient.mk JA (f.coeff n), hb_notpB⟩
    have hregU : IsSMulRegular U (algebraMap C0 U fB) := by
      have hreg0 : IsSMulRegular U ((fB.map (algebraMap B Bp) : U)) := by
        apply polynomial_isSMulRegular_of_isUnit_coeff (n := n)
        simpa [fB, Polynomial.coeff_map] using hcoeffUnit
      change IsSMulRegular U ((Polynomial.mapRingHom (algebraMap B Bp)) fB)
      simpa [Polynomial.coe_mapRingHom] using hreg0
    let T : Type _ := S ⧸ Jloc
    have hIJS : I ≤ Ideal.comap (algebraMap A[X] S) Jloc := by
      intro x hx
      change algebraMap A[X] S x ∈ Jloc
      rw [hJloc]
      exact Ideal.mem_map_of_mem _ hx
    let qmap : A[X] ⧸ I →+* T := Ideal.quotientMap Jloc (algebraMap A[X] S) hIJS
    letI : Algebra C0 T := (qmap.comp e.toRingHom).toAlgebra
    let π : A[X] →+* C0 := e.symm.toRingHom.comp (Ideal.Quotient.mk I)
    let N0 : Submonoid C0 := Q'.primeCompl.map π
    have hπsurj : Function.Surjective π := by
      intro y
      obtain ⟨x, hx⟩ := Ideal.Quotient.mk_surjective (e y)
      refine ⟨x, ?_⟩
      apply e.injective
      change e (π x) = e y
      dsimp [π]
      rw [RingEquiv.apply_symm_apply, hx]
    have hcomp : (Ideal.Quotient.mk Jloc).comp (algebraMap A[X] S) =
        (algebraMap C0 T).comp π := by
      apply RingHom.ext
      intro x
      change Ideal.Quotient.mk Jloc (algebraMap A[X] S x) = qmap (e (π x))
      dsimp [π, qmap]
      rw [RingEquiv.apply_symm_apply]
      rw [Ideal.quotientMap_mk]
      exact (Ideal.Quotient.mk_algebraMap A[X] Jloc x).symm
    have hkerπ : RingHom.ker π = I := by
      ext x
      simp [π, Ideal.Quotient.eq_zero_iff_mem]
    have hkerle : RingHom.ker (Ideal.Quotient.mk Jloc) ≤
        Ideal.map (algebraMap A[X] S) (RingHom.ker π) := by
      rw [Ideal.mk_ker, hkerπ, hJloc]
    haveI hLocT : IsLocalization N0 T := by
      dsimp [N0]
      exact IsLocalization.of_surjective Q'.primeCompl S π hπsurj
        (Ideal.Quotient.mk Jloc) Ideal.Quotient.mk_surjective hcomp hkerle
    let M0 : Submonoid C0 := pB.primeCompl.map (C : B →+* C0)
    haveI hLocU : IsLocalization M0 U := by
      dsimp [M0, U, C0, Bp]
      exact Polynomial.isLocalization pB.primeCompl Bp
    have hMN : M0 ≤ N0 := by
      rintro z ⟨b, hb, rfl⟩
      obtain ⟨a, rfl⟩ := Ideal.Quotient.mk_surjective b
      have haP : a ∉ P := by
        intro ha
        exact hb (Ideal.mem_map_of_mem (Ideal.Quotient.mk JA) ha)
      refine ⟨C a, ?_, ?_⟩
      · exact fun hCa => haP hCa
      · change π (C a) = C (Ideal.Quotient.mk JA a)
        apply e.injective
        dsimp [π]
        rw [RingEquiv.apply_symm_apply]
        change Ideal.Quotient.mk I (C a) = e (C (Ideal.Quotient.mk JA a))
        rw [show (C (Ideal.Quotient.mk JA a) : C0) =
            (C a : A[X]).map (Ideal.Quotient.mk JA) by rw [Polynomial.map_C]]
        exact (Ideal.polynomialQuotientEquivQuotientPolynomial_map_mk JA (C a)).symm
    letI algUT := IsLocalization.localizationAlgebraOfSubmonoidLe (R := C0) U T M0 N0 hMN
    letI towerCUT := IsLocalization.localization_isScalarTower_of_submonoid_le (R := C0)
      U T M0 N0 hMN
    haveI locUT := IsLocalization.isLocalization_of_submonoid_le (R := C0) U T M0 N0 hMN
    letI smulTT : SMul T T := ⟨fun x y => x * y⟩
    have hregT_U : IsSMulRegular T (algebraMap U T (algebraMap C0 U fB)) :=
      IsSMulRegular.of_isLocalization T (N0.map (algebraMap C0 U)) hregU
    have hregT_C0 : IsSMulRegular T (algebraMap C0 T fB) := by
      simpa [IsScalarTower.algebraMap_apply C0 U T] using hregT_U
    have he_fB : e fB = Ideal.Quotient.mk I f := by
      dsimp [e, fB, I, JA]
      exact Ideal.polynomialQuotientEquivQuotientPolynomial_map_mk (Ideal.ofList rsA) f
    have hscalar : algebraMap S T (algebraMap A[X] S f) = algebraMap C0 T fB := by
      change Ideal.Quotient.mk Jloc (algebraMap A[X] S f) = qmap (e fB)
      rw [he_fB]
      dsimp [qmap]
      rw [Ideal.quotientMap_mk]
      exact (Ideal.Quotient.mk_algebraMap A[X] Jloc f).symm
    have hregT_S : IsSMulRegular T (algebraMap S T (algebraMap A[X] S f)) := by
      rwa [hscalar]
    intro x y hxy
    exact hregT_S (by
      change (algebraMap S T (algebraMap A[X] S f)) * x =
        (algebraMap S T (algebraMap A[X] S f)) * y
      change (Ideal.Quotient.mk Jloc (algebraMap A[X] S f)) * x =
        (Ideal.Quotient.mk Jloc (algebraMap A[X] S f)) * y at hxy
      simpa only [Ideal.Quotient.mk_algebraMap] using hxy)
  · have hnot : ¬ ∀ x, x ∈ I → x ∈ Q' := hIle
    push_neg at hnot
    obtain ⟨x, hxI, hxQ⟩ := hnot
    have hxunit : IsUnit (algebraMap A[X] S x) := by
      change IsUnit (algebraMap A[X] (Localization.AtPrime Q') x)
      exact IsLocalization.map_units (M := Q'.primeCompl) (Localization.AtPrime Q') ⟨x, hxQ⟩
    have hJmaptop : Ideal.map (algebraMap A[X] S) I = ⊤ :=
      Ideal.eq_top_of_isUnit_mem (Ideal.map (algebraMap A[X] S) I)
        (Ideal.mem_map_of_mem (algebraMap A[X] S) hxI) hxunit
    have hJtop : Jloc = ⊤ := hJloc.trans hJmaptop
    have hsub : N = ⊤ := by
      dsimp [N]
      rw [hJtop]
      exact Submodule.top_smul (⊤ : Submodule S S)
    intro a b _
    obtain ⟨a0, rfl⟩ := Submodule.Quotient.mk_surjective N a
    obtain ⟨b0, rfl⟩ := Submodule.Quotient.mk_surjective N b
    rw [Submodule.Quotient.eq, hsub]
    trivial

/-- **Case B (algebraic fibre).** When `Q'` strictly dominates `P[X]` and `rsA`
is a length-`ht P` weakly regular sequence generating (up to radical) the
maximal ideal of `A_P`, appending one polynomial `f ∈ Q' \ P[X]` (a nonzerodivisor
in the Artinian-local fibre by McCoy) yields a length-`ht P + 1` weakly regular
sequence in `Q'` on `(A[X])_{Q'}`. -/
theorem polyStepPrime_caseB {A : Type*} [CommRing A] [IsNoetherianRing A] [IsDomain A]
    {P : Ideal A} [P.IsPrime] {Q' : Ideal A[X]} [Q'.IsPrime]
    (hPQ : Ideal.comap (C : A →+* A[X]) Q' = P)
    (rsA : List A) (hmemA : ∀ r ∈ rsA, r ∈ P)
    (hregA : IsWeaklyRegular (Localization.AtPrime P)
      (rsA.map (algebraMap A (Localization.AtPrime P))))
    (hPh : P.height = rsA.length) (hbig : (rsA.length : ℕ∞) < Q'.height) :
    ∃ rs : List A[X], rs.length = rsA.length + 1 ∧ (∀ r ∈ rs, r ∈ Q') ∧
      IsWeaklyRegular (Localization.AtPrime Q')
        (rs.map (algebraMap A[X] (Localization.AtPrime Q'))) := by
  -- `f ∈ Q' \ P[X]` exists because `P[X] ⊊ Q'` (heights: `ht P[X] ≤ ht P < ht Q'`).
  have hstrict : Ideal.map (C : A →+* A[X]) P < Q' := by
    refine lt_of_le_of_ne ?_ ?_
    · rw [← hPQ]; exact Ideal.map_comap_le
    · intro heq
      have h1 : Q'.height ≤ P.height := heq ▸ height_map_C_le P
      rw [hPh] at h1
      exact absurd (lt_of_lt_of_le hbig h1) (lt_irrefl _)
  obtain ⟨f, hfQ, hfP⟩ := SetLike.exists_of_lt hstrict
  have hcA := caseA_transport hPQ hregA
  refine ⟨rsA.map C ++ [f], by simp, ?_, ?_⟩
  · intro r hr
    rcases List.mem_append.mp hr with hr | hr
    · obtain ⟨a, ha, rfl⟩ := List.mem_map.mp hr
      exact hstrict.le (Ideal.mem_map_of_mem C (hmemA a ha))
    · rw [List.mem_singleton.mp hr]; exact hfQ
  · rw [List.map_append, isWeaklyRegular_append_iff]
    refine ⟨hcA, ?_⟩
    rw [List.map_cons, List.map_nil, isWeaklyRegular_singleton_iff]
    exact mccoy_fibre rsA f (by rw [hPQ]; exact hfP)

/-- **Inductive step over a univariate polynomial extension (localized).**
Assuming the localized grade ≥ height statement for all primes of `A`, it holds
for all primes of `A[X]`. This is the geometric heart: the fibre of
`Spec A[X] → Spec A` has dimension ≤ 1, so a height-`h` prime `Q'` of `A[X]`
lies over a prime `P` of `A` with `ht P ≥ h` (extended case) or `ht P = h-1`
(algebraic case, where an extra polynomial nonzerodivisor is appended). -/
theorem polyStepPrime {A : Type*} [CommRing A] [IsNoetherianRing A] [IsDomain A]
    (hIH : ∀ (P : Ideal A) [P.IsPrime] (k : ℕ), (k : ℕ∞) ≤ P.height →
      ∃ rs : List A, rs.length = k ∧ (∀ r ∈ rs, r ∈ P) ∧
        IsWeaklyRegular (Localization.AtPrime P)
          (rs.map (algebraMap A (Localization.AtPrime P))))
    (Q' : Ideal A[X]) [Q'.IsPrime] (h : ℕ) (hh : (h : ℕ∞) ≤ Q'.height) :
    ∃ rs : List A[X], rs.length = h ∧ (∀ r ∈ rs, r ∈ Q') ∧
      IsWeaklyRegular (Localization.AtPrime Q')
        (rs.map (algebraMap A[X] (Localization.AtPrime Q'))) := by
  set P := Ideal.comap (C : A →+* A[X]) Q' with hP
  haveI : P.IsPrime := inferInstance
  by_cases hcase : (h : ℕ∞) ≤ P.height
  · -- **Case A**: `h ≤ ht P`; the pushed-forward `P`-sequence already has length `h`.
    obtain ⟨rsA, hlen, hmem, hreg⟩ := hIH P h hcase
    refine ⟨rsA.map C, by rw [List.length_map, hlen], ?_, caseA_transport hP.symm hreg⟩
    intro r hr
    obtain ⟨a, ha, rfl⟩ := List.mem_map.mp hr
    have hmem' := hmem a ha; rw [hP] at hmem'; exact Ideal.mem_comap.mp hmem'
  · -- **Case B**: `ht P < h`; then `h = ht P + 1` and one extra polynomial is appended.
    have hb : Q'.height ≤ P.height + 1 := by rw [hP]; exact heightbound Q'
    have hlt : P.height < (h : ℕ∞) := lt_of_not_ge hcase
    have hPne : P.height ≠ ⊤ := (lt_of_lt_of_le hlt le_top).ne
    obtain ⟨m, hm0⟩ := WithTop.ne_top_iff_exists.mp hPne
    have hm : (m : ℕ∞) = P.height := by exact_mod_cast hm0
    rw [← hm] at hlt hb
    have hmlt : m < h := by exact_mod_cast hlt
    have hle1' : h ≤ m + 1 := by exact_mod_cast (le_trans hh hb)
    have hmh : h = m + 1 := by omega
    obtain ⟨rsA, hlenA, hmemA, hregA⟩ := hIH P m (le_of_eq hm)
    have hbig : (rsA.length : ℕ∞) < Q'.height := by
      rw [hlenA]; exact lt_of_lt_of_le hlt hh
    have hPh : P.height = (rsA.length : ℕ∞) := by rw [hlenA]; exact hm.symm
    obtain ⟨rs, hlen, hmem, hreg⟩ := polyStepPrime_caseB hP.symm rsA hmemA hregA hPh hbig
    exact ⟨rs, by rw [hlen, hlenA, hmh], hmem, hreg⟩

/-- **Arbitrary-field grade ≥ height (auxiliary, induction on the number of
variables).** -/
theorem grade_ge_height_field_aux {L : Type*} [Field L] :
    ∀ (n : ℕ) (Q : Ideal (MvPolynomial (Fin n) L)) [Q.IsPrime] (h : ℕ),
      (h : ℕ∞) ≤ Q.height →
      ∃ rs : List (MvPolynomial (Fin n) L),
        rs.length = h ∧ (∀ r ∈ rs, r ∈ Q) ∧
        IsWeaklyRegular (Localization.AtPrime Q)
          (rs.map (algebraMap (MvPolynomial (Fin n) L) (Localization.AtPrime Q))) := by
  intro n
  induction n with
  | zero =>
    intro Q hQ h hh
    haveI := hQ
    have hdim : ringKrullDim (MvPolynomial (Fin 0) L) = 0 := by
      rw [MvPolynomial.ringKrullDim_of_isNoetherianRing, ringKrullDim_eq_zero_of_field L]; simp
    have h1 : Q.height ≤ ringKrullDim (MvPolynomial (Fin 0) L) :=
      Ideal.height_le_ringKrullDim_of_ne_top hQ.ne_top
    rw [hdim] at h1
    have hz : Q.height ≤ 0 := by exact_mod_cast h1
    have : h = 0 := Nat.le_zero.mp (by exact_mod_cast le_trans hh hz)
    subst this
    exact ⟨[], rfl, by simp, by simp [IsWeaklyRegular.nil]⟩
  | succ n ih =>
    intro Q hQ h hh
    haveI := hQ
    let φ : MvPolynomial (Fin (n + 1)) L ≃+* (MvPolynomial (Fin n) L)[X] :=
      (MvPolynomial.finSuccEquiv L n).toRingEquiv
    refine transport φ Q h ?_
    haveI : (Ideal.map φ Q).IsPrime := Ideal.map_isPrime_of_equiv φ
    refine polyStepPrime (fun P hP k hk => @ih P hP k hk) (Ideal.map φ Q) h ?_
    rw [RingEquiv.height_map]; exact hh

/-- **Arbitrary-field grade ≥ height.** For any field `L`, any prime `Q` of
`L[x₁,…,xₙ]`, and any `h ≤ height Q`, the localization at `Q` carries a weakly
regular sequence of length `h` whose members lie in `Q`. -/
theorem grade_ge_height_field {L : Type*} [Field L] {n : ℕ}
    (Q : Ideal (MvPolynomial (Fin n) L)) [Q.IsPrime]
    (h : ℕ) (hh : (h : ℕ∞) ≤ Q.height) :
    ∃ rs : List (MvPolynomial (Fin n) L),
      rs.length = h ∧ (∀ r ∈ rs, r ∈ Q) ∧
      IsWeaklyRegular (Localization.AtPrime Q)
        (rs.map (algebraMap (MvPolynomial (Fin n) L) (Localization.AtPrime Q))) :=
  grade_ge_height_field_aux n Q h hh

end GradeHeight

/-- **T2-W0.** Every prime of a polynomial ring over an algebraically closed
field contains, locally, a weakly regular sequence of length its height. -/
theorem grade_ge_height
    {K : Type*} [Field K] [IsAlgClosed K] {n : ℕ}
    (Q : Ideal (MvPolynomial (Fin n) K)) [Q.IsPrime]
    (h : ℕ) (hh : (h : ℕ∞) ≤ Q.height) :
    ∃ rs : List (MvPolynomial (Fin n) K),
      rs.length = h ∧ (∀ r ∈ rs, r ∈ Q) ∧
      IsWeaklyRegular (Localization.AtPrime Q)
        (rs.map (algebraMap (MvPolynomial (Fin n) K) (Localization.AtPrime Q))) :=
  GradeHeight.grade_ge_height_field Q h hh
